name: Quality

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21', '1.22']
    name: Go ${{ matrix.go }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Running test
        run: go test -cover -v $(go list -v ./...)

